### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by liebig** [danShumway/serverboy.js#1]
Serverboy is a very intersting project but I wonder if this project is still alive?

**Comment by danShumway** [comment]
It's more like its in a coma:

 - it looks like its dead, but could theoretically wake up at any time.
 - if other projects get in the way, it might be a long time before it wakes up.
 - it might look and act differently when it finally does wake up.

When it does wake up, you're most likely going to see commits on https://gitlab.com/piglet-plays/serverboy.js, not here (although I can mirror the repository if there are enough people on Github who want me to).

What's your specific interest? I've got other stuff on my plate right now, but I could be persuaded to pay more attention to Serverboy if it wasn't just me using it.

**Comment by liebig** [comment]
Thank you for the quick answer. I was always looking for a GameBoy emulator for NodeJS without dependencies and I came across your library by accident. I would like to use the emulator with friends online and will test it the next days. At first sight Serverboy looks great, so please don't let the coma patient die ;)

**Comment by danShumway** [comment]
Will be starting up development soon, so this issue can be closed for now.

Most of my stories will be tracked on [Gitlab](https://gitlab.com/piglet-plays/serverboy.js), but I've set up that repository to mirror to this one. Just bear in mind that I might be slightly slower to respond to issues on Github, and that I'll only be responding to 3rd-party issues, not mirroring over development tasks or tracking milestones.
