### ISSUE TITLE
pressKey expects a string even though docs say to pass from KEYMAP

### ISSUE THREAD

**Issue by suchipi** [danShumway/serverboy.js#3]
The [docs say that `pressKey` expects a value from `KEYMAP`](https://github.com/danShumway/serverboy.js/blob/master/docs/api.md#presskey), but [`pressKey` is actually assuming it will receive a string](https://github.com/danShumway/serverboy.js/blob/68f0ac88b5b280f64de2c8ae6d57d8a84cbe3628/src/interface.js#L153). 

Because `pressKeys` calls `pressKey` internally, this affects `pressKeys` as well.

Removing [this line](https://github.com/danShumway/serverboy.js/blob/68f0ac88b5b280f64de2c8ae6d57d8a84cbe3628/src/interface.js#L153) will fix the issue.

**Comment by danShumway** [comment]
Thanks for the bug!

I guess a couple of people actually use this, and while it is in alpha state and the API isn't nailed down, I'm loathe to change it too much under their feet. So I'm going to change the function to accept both strings and numbers.

Will push a new version soonish.

**Comment by danShumway** [comment]
Sorry for the long delay, version `0.0.7` should be live at https://www.npmjs.com/package/serverboy

A bunch of real-life kind of got in the way, but I am looking at setting up some better testing/documentation around this stuff, maybe cleaning up the API a little.

Closing this for now, feel free to reopen if you notice any issues.

**Comment by suchipi** [comment]
Thank you!
